import { Property } from './types';

export const mockProperties: Property[] = [
    {
        id: 1,
        title: 'Modern Downtown Apartment',
        description: 'A beautiful modern apartment in the heart of downtown with stunning city views. Features include hardwood floors, stainless steel appliances, and a private balcony.',
        price: 350000,
        location: 'Downtown, City Center',
        bedrooms: 2,
        bathrooms: 2,
        area: 1200,
        imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        amenities: ['Parking', 'Gym', 'Swimming Pool', 'Security'],
        contactEmail: 'contact@dreamsproperty.com',
        contactPhone: '+1 (555) 123-4567',
        createdAt: '2023-01-15T10:30:00',
    },
    {
        id: 2,
        title: 'Suburban Family Home',
        description: 'Spacious family home in a quiet suburban neighborhood. Perfect for raising a family with a large backyard, modern kitchen, and close to excellent schools.',
        price: 550000,
        location: 'Oakridge Suburb',
        bedrooms: 4,
        bathrooms: 3,
        area: 2500,
        imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233',
        amenities: ['Garden', 'Garage', 'Fireplace', 'Central Heating/AC'],
        contactEmail: 'contact@dreamsproperty.com',
        contactPhone: '+1 (555) 123-4567',
        createdAt: '2023-02-20T14:15:00',
    },
    {
        id: 3,
        title: 'Luxury Beach Villa',
        description: 'Breathtaking beach villa with direct access to the shoreline. Featuring panoramic ocean views, a private pool, and high-end finishes throughout.',
        price: 1200000,
        location: 'Coastal Heights',
        bedrooms: 5,
        bathrooms: 4.5,
        area: 3800,
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
        amenities: ['Private Pool', 'Beach Access', 'Home Theater', 'Wine Cellar', 'Smart Home'],
        contactEmail: 'luxury@dreamsproperty.com',
        contactPhone: '+1 (555) 987-6543',
        createdAt: '2023-03-10T09:45:00',
    },
]; 