[build]
  base = "client/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  REACT_APP_API_URL = "https://dreams-property-server.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 